### PR TITLE
Add TX2 Content

### PR DESCRIPTION
**Pull request by cpennington**
I'm planning to add the TX2 Weapons as well

### CODE REVIEW

**Comment by cpennington** [comment]
@voidstate, anything I can do to get this merged sooner?

**Comment by unstoppablecarl** [comment]
@voidstate don't leave us hanging.

**Comment by voidstate** [comment]
Thanks for the changes. I just got back from holiday so will test them this week and push them to the live site.

**Comment by unstoppablecarl** [comment]
Should we add the long descriptions?

**Pull request merged**
